# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kj9Ae1O65zB1bj9-7AftKLAdfZ1qdLsc
"""

pip install yfinance pandas numpy scikit-learn lightgbm xgboost optuna shap lime matplotlib arch

import yfinance as yf
import numpy as np
import pandas as pd

# --- Adım 1: Veri ---
df = yf.download("^GSPC", start="2010-01-01", end="2024-12-31", auto_adjust=True)
df = df[["Close", "Volume"]].dropna()
df.columns = ["close", "volume"]
df["ret"] = np.log(df["close"]).diff()
df = df.dropna()

# --- Adım 2: Hedef (gelecek 5 günün gerçekleşen oynaklığı) ---
HORIZON = 5
df["target_vol"] = df["ret"].rolling(HORIZON).std().shift(-HORIZON) * np.sqrt(252)

# --- Adım 3: Öznitelikler (yalnızca geçmiş veriden) ---
for w in [5, 10, 22, 66]:
    df[f"vol_{w}"] = df["ret"].rolling(w).std() * np.sqrt(252)
df["abs_ret"] = df["ret"].abs()
for lag in [1, 2, 3, 5]:
    df[f"abs_ret_lag{lag}"] = df["abs_ret"].shift(lag)
df["ret_lag1"] = df["ret"].shift(1)
df["vol_chg"] = np.log(df["volume"] + 1).diff()   # +1 ile log(0) sorununu baştan engelledik
df["vol_ma22"] = df["volume"].rolling(22).mean()
df["dow"] = df.index.dayofweek
df["month"] = df.index.month

# --- Temizlik: NaN + inf birlikte ---
df = df.replace([np.inf, -np.inf], np.nan).dropna()

print("Son boyut:", df.shape)
print("target_vol var mı?:", "target_vol" in df.columns)
print("inf sayısı:", np.isinf(df.select_dtypes(include=[np.number])).sum().sum())
df.head()

from sklearn.model_selection import TimeSeriesSplit

# Öznitelik / hedef ayrımı
feature_cols = [c for c in df.columns
                if c not in ["close", "volume", "ret", "abs_ret", "target_vol"]]
X = df[feature_cols]
y = df["target_vol"]

print("Kullanılan öznitelikler:", feature_cols)

# Kronolojik bölme: ilk %80 eğitim, son %20 test
split_idx = int(len(df) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print(f"Eğitim: {X_train.shape[0]} satır  |  Test: {X_test.shape[0]} satır")
print(f"Eğitim dönemi: {X_train.index.min().date()} → {X_train.index.max().date()}")
print(f"Test dönemi:  {X_test.index.min().date()} → {X_test.index.max().date()}")

# Doğrulama için zaman serisi cross-validation
tscv = TimeSeriesSplit(n_splits=5)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def evaluate(y_true, y_pred, name=""):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    r2   = r2_score(y_true, y_pred)
    print(f"{name:20s} | RMSE: {rmse:.4f} | MAE: {mae:.4f} | MAPE: {mape:.2f}% | R²: {r2:.4f}")
    return {"model": name, "RMSE": rmse, "MAE": mae, "MAPE": mape, "R2": r2}

results = []

# --- Baseline 1: Naive (son 5 günün oynaklığı = gelecek oynaklık tahmini) ---
naive_pred = X_test["vol_5"].values
results.append(evaluate(y_test.values, naive_pred, "Naive (vol_5)"))

from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# Pipeline: önce ölçekle, sonra Ridge
ridge_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge())
])

# alpha için arama uzayı
param_grid = {"model__alpha": [0.001, 0.01, 0.1, 1, 10, 100, 1000]}

# Zaman serisi CV ile, RMSE'yi minimize ederek ara
ridge_search = GridSearchCV(
    ridge_pipe,
    param_grid,
    cv=tscv,                              # Adım 4'teki TimeSeriesSplit
    scoring="neg_root_mean_squared_error",
    n_jobs=-1
)
ridge_search.fit(X_train, y_train)

print("En iyi alpha:", ridge_search.best_params_)
print("CV RMSE:", -ridge_search.best_score_)

# Test setinde değerlendir
ridge_pred = ridge_search.predict(X_test)
results.append(evaluate(y_test.values, ridge_pred, "Ridge"))

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf_param = {
    "n_estimators":      [200, 400, 600],
    "max_depth":         [4, 6, 8, 12, None],
    "min_samples_leaf":  [1, 5, 10, 20],
    "max_features":      ["sqrt", 0.5, 1.0],
}

rf_search = RandomizedSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    rf_param,
    n_iter=30,                 # 30 rastgele kombinasyon dene
    cv=tscv,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1
)
rf_search.fit(X_train, y_train)

print("En iyi parametreler:", rf_search.best_params_)
print("CV RMSE:", -rf_search.best_score_)

rf_pred = rf_search.predict(X_test)
results.append(evaluate(y_test.values, rf_pred, "Random Forest"))

import optuna
import lightgbm as lgb
from sklearn.model_selection import cross_val_score

optuna.logging.set_verbosity(optuna.logging.WARNING)  # çıktıyı sessizleştir

def objective(trial):
    params = {
        "n_estimators":     trial.suggest_int("n_estimators", 100, 800),
        "learning_rate":    trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth":        trial.suggest_int("max_depth", 2, 8),
        "num_leaves":       trial.suggest_int("num_leaves", 7, 63),
        "min_child_samples":trial.suggest_int("min_child_samples", 5, 50),
        "subsample":        trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "random_state": 42, "n_jobs": -1, "verbose": -1,
    }
    model = lgb.LGBMRegressor(**params)
    # TimeSeriesSplit ile CV RMSE (negatif), ortalamasını al
    scores = cross_val_score(model, X_train, y_train, cv=tscv,
                             scoring="neg_root_mean_squared_error")
    return -scores.mean()   # Optuna minimize edecek

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("En iyi parametreler:", study.best_params)
print("En iyi CV RMSE:", study.best_value)

# En iyi parametrelerle modeli eğit ve test et
best_lgb = lgb.LGBMRegressor(**study.best_params, random_state=42, n_jobs=-1, verbose=-1)
best_lgb.fit(X_train, y_train)
lgb_pred = best_lgb.predict(X_test)
results.append(evaluate(y_test.values, lgb_pred, "LightGBM"))

from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt

perm = permutation_importance(
    best_lgb, X_test, y_test,
    n_repeats=30, random_state=42,
    scoring="neg_root_mean_squared_error"
)

# Önem sırasına göre diz
perm_df = pd.DataFrame({
    "feature": X_test.columns,
    "importance": perm.importances_mean,
    "std": perm.importances_std
}).sort_values("importance", ascending=False)

print(perm_df)

# Görselleştir
plt.figure(figsize=(8, 6))
plt.barh(perm_df["feature"], perm_df["importance"], xerr=perm_df["std"])
plt.gca().invert_yaxis()
plt.xlabel("RMSE artışı (önem)")
plt.title("Permutation Feature Importance — LightGBM")
plt.tight_layout()
plt.show()

import shap

# Tree modelleri için hızlı ve exact explainer
explainer = shap.TreeExplainer(best_lgb)
shap_values = explainer.shap_values(X_test)

# --- GLOBAL: summary plot (beeswarm) ---
shap.summary_plot(shap_values, X_test, show=True)

# --- LOKAL: tek bir tahminin waterfall açıklaması ---
shap.initjs()
idx = 0  # test setindeki ilk gün; istediğin günü seçebilirsin
shap.plots._waterfall.waterfall_legacy(
    explainer.expected_value,
    shap_values[idx],
    feature_names=X_test.columns,
    max_display=10
)

# Test setinde en yüksek gerçek oynaklığa sahip günü bul
idx = np.argmax(y_test.values)
print("Seçilen gün:", X_test.index[idx].date(), "| Gerçek oynaklık:", round(y_test.values[idx], 3))

shap.plots._waterfall.waterfall_legacy(
    explainer.expected_value,
    shap_values[idx],
    feature_names=X_test.columns,
    max_display=10
)

from lime.lime_tabular import LimeTabularExplainer

lime_explainer = LimeTabularExplainer(
    training_data=X_train.values,
    feature_names=X_train.columns.tolist(),
    mode="regression",
    random_state=42
)

# Yüksek oynaklıklı günü açıkla (yukarıdaki idx ile aynı)
exp = lime_explainer.explain_instance(
    X_test.values[idx],
    best_lgb.predict,
    num_features=10
)

# Notebook'ta görsel olarak göster
exp.show_in_notebook(show_table=True)

# Veya grafik olarak
fig = exp.as_pyplot_figure()
plt.tight_layout()
plt.show()

from arch import arch_model

# GARCH getirileri yüzde olarak ister (sayısal stabilite için)
ret_pct = df["ret"] * 100
split_idx = int(len(df) * 0.8)   # ML ile aynı bölme noktası

# Test dönemindeki her gün için "kayan pencere" GARCH tahmini
garch_preds = []
test_index = df.index[split_idx:]

for i in range(split_idx, len(df)):
    # O güne kadarki tüm getirilerle modeli eğit (genişleyen pencere)
    train_ret = ret_pct.iloc[:i]
    am = arch_model(train_ret, vol="Garch", p=1, q=1, dist="normal")
    res = am.fit(disp="off")
    # 5 gün ileri tahmin
    fc = res.forecast(horizon=HORIZON, reindex=False)
    # 5 günlük varyans toplamı → std → yıllıklaştır → %100'e geri böl
    var_5d = fc.variance.values[-1, :].sum()
    vol_5d_annual = np.sqrt(var_5d) / 100 * np.sqrt(252 / HORIZON)
    garch_preds.append(vol_5d_annual)

garch_preds = np.array(garch_preds)
results.append(evaluate(y_test.values, garch_preds, "GARCH(1,1)"))